### ISSUE TITLE
Use local images

### ISSUE THREAD

**Issue by derba** [bsycorp/kind#14]
I build images locally using docker build. Then I want to use them without uploading to a public/private repo. How to do that?

Currently I use `docker save` + `docker cp` + `docker load` in kind container. And in deployment.yaml I added `imagePullPolicy: IfNotPresent`. That kinda works and can be scripted. Do you have any better idea? What about something like this: https://stackoverflow.com/a/42564211

**Comment by nhoughto** [comment]
So you can achieve this fairly easily, basically by doing what the `minikube docker-env` actually does under the cover (sort of).


1. Start `kind` with an extra port mapping for the Docker TCP port, `2375`
```
docker run -it --privileged -p 2375:2375 -p 8443:8443 -p 10080:10080 bsycorp/kind:latest-1.10
```

2. Point your local docker client at the `kind` hosted docker daemon
```
$ export DOCKER_HOST=tcp://127.0.0.1:2375
$ docker images
REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-proxy-amd64                v1.10.12            8288a8569fc4        2 months ago        98.3MB
k8s.gcr.io/kube-apiserver-amd64            v1.10.12            4fb6852fef47        2 months ago        228MB
k8s.gcr.io/kube-scheduler-amd64            v1.10.12            dae0cbcd1f2c        2 months ago        51.2MB
k8s.gcr.io/kube-controller-manager-amd64   v1.10.12            1e915d6a5a83        2 months ago        151MB
k8s.gcr.io/coredns                         1.2.2               367cdc8433a4        5 months ago        39.2MB
nginx                                      1.13                ae513a47849c        9 months ago        109MB
k8s.gcr.io/etcd-amd64                      3.1.12              52920ad46f5b        11 months ago       193MB
k8s.gcr.io/kube-addon-manager              v8.6                9c16409588eb        12 months ago       78.4MB
k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64     1.14.8              c2ce1ffb51ed        13 months ago       41MB
k8s.gcr.io/k8s-dns-sidecar-amd64           1.14.8              6f7f2dc7fab5        13 months ago       42.2MB
k8s.gcr.io/k8s-dns-kube-dns-amd64          1.14.8              80cc5ea4b547        13 months ago       50.5MB
k8s.gcr.io/pause-amd64                     3.1                 da86e6ba6ca1        14 months ago       742kB
```

3. Run `docker build` etc as you would normally do and your images will be built in `kind` docker daemon rather than your local one, saving the copy step. If you are using the CI tool `services` integration than `2375` is accessible on `localhost` automatically.
