### ISSUE TITLE
Sharing image cache with host

### ISSUE THREAD

**Issue by moltar** [bsycorp/kind#16]
It would be great to be able to cache Docker images on the host, so that future spin ups would speed up even more.

It is quite possible to share image cache with DIND approach:

The following works:

```sh
docker run --rm -it --privileged \
   --volume="/var/run/docker.sock:/var/run/docker.sock" \
   docker:latest sh
```

Now issuing `docker images` inside DIND, shows host's docker images.

However, when trying the same trick with `kind`:

```sh
docker run --rm -it --privileged -p 8443:8443 -p 10080:10080 \
   --volume="/var/run/docker.sock:/var/run/docker.sock" \
   bsycorp/kind:latest-1.10
```

Then the container boot fails with:

```
2019-03-29 01:55:35,120 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2019-03-29 01:55:35,129 INFO RPC interface 'supervisor' initialized
2019-03-29 01:55:35,129 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-03-29 01:55:35,129 INFO supervisord started with pid 1
2019-03-29 01:55:36,133 INFO spawned: 'start' with pid 8
Clean up..
2019-03-29 01:55:36,144 INFO exited: start (exit status 1; not expected)
2019-03-29 01:55:37,148 INFO spawned: 'start' with pid 12
Clean up..
2019-03-29 01:55:37,159 INFO exited: start (exit status 1; not expected)
2019-03-29 01:55:39,169 INFO spawned: 'start' with pid 16
Clean up..
2019-03-29 01:55:39,180 INFO exited: start (exit status 1; not expected)
2019-03-29 01:55:42,195 INFO spawned: 'start' with pid 20
Clean up..
2019-03-29 01:55:42,208 INFO exited: start (exit status 1; not expected)
2019-03-29 01:55:42,209 INFO gave up: start entered FATAL state, too many start retries too quickly
^C2019-03-29 01:55:43,660 WARN received SIGINT indicating exit request
```

Any ideas on how to fix this?

----

P.S. Thank you for building this, it helps tremendously to test out Kubernetes deployments.

**Comment by nhoughto** [comment]
So the current behaviour is to actually cache images IN `kind` itself (for kubernetes, nginx ingress and other custom ones via https://github.com/bsycorp/kind#how-to-pull-images-from-a-private-registry. This bakes it into the kind image itself and requires you to build your own kind images, but speeds up `kind` boot up.

I think what you are suggesting is kind of the opposite? Rather than build custom `kind` images to prevent pulling remote images, get `kind` to use the hosts docker daemon and thus cache? Seems like it should be possible but could present a few problems.

1. It means `kind` would have root access to the host. You may or may not care about this.
2. It means kubernetes that `kind` starts would have containers running on the host docker daemon, and thus inherit its networking etc as well as its cache. Seems less ephemeral? Could cause problems..
3. This likely wouldn't be possible in cloud CI environments, and it wouldn't work as a CI "service", as generally a docker daemon IS a CI "service"..

Hopefully i've understood your scenario properly, have you tried building a custom version of `kind` to cache your images for you? That is the intended and supported approach to speeding things up.

**Comment by moltar** [comment]
> I think what you are suggesting is kind of the opposite? Rather than build custom kind images to prevent pulling remote images, get kind to use the hosts docker daemon and thus cache? Seems like it should be possible but could present a few problems.

> Hopefully i've understood your scenario properly, have you tried building a custom version of kind to cache your images for you? That is the intended and supported approach to speeding things up.

My use case is to test various Kubernetes deployments and setups. I am running tests with many different variations/images. This has many moving parts and images getting pulled each time. Thus I cannot pre-build a `kind` image with the needed images baked-in. I mean, I probably could find all the images I need and build them in, but then during dev cycle I'll add another image, and boom, have to rebuild it again, thus not sure if the time saving from downloading images would be offset by rebuilding a `kind` image.

> This likely wouldn't be possible in cloud CI environments, and it wouldn't work as a CI "service", as generally a docker daemon IS a CI "service"..

That would be fine, as actual CI is ran much less often than during the dev cycle where I have to reboot the container many times and then all images are getting pulled again. This is especially bothersome on slow internet connections.

The other option is to setup some kind of local caching mechanism (proxy) to cache image downloads. But it seems pretty heavy-weight too and would lack the features provided by `docker` CLI to manage/remove images.

Btw, this mostly not a huge deal. I thought there might be a quick solution with the volume maps and I am missing something. But if not, I don't think it's worth any dev effort.

Thanks!

**Comment by nhoughto** [comment]
Ok your scenario sounds different to our intent, one kinda ghetto way to do it would be to start `kind` with its own daemon as per normal, and `docker image save` `docker image import` from `host->kind` so that your host docker cache can be used as a local store of images, and do a cheap push from host to `kind` daemon. This saves the internet roundtrip, saves you from building custom `kind` images and fits with the current way `kind` hangs together :+1:

**Comment by moltar** [comment]
Ok, thanks. I will try this ... eventually 😁 

I will close the issue for now then.
