### ISSUE TITLE
docker does not clean up volume after deleting cluster

### ISSUE THREAD

**Issue by xial-thu** [bsycorp/kind#25]
/kind: bug

# What happened
Hi, I'm using kind in my gitlab-CI. My script is
```bash
e2e-test:
  stage: test
  tags:
    - mpirun-controller
  dependencies:
    - deps
  before_script:
    - docker run -tid --name=kind --privileged -p 8444:8443 -p 10080:10080 registry.sensetime.com/share/kind:latest-1.12
    - export PATH="/go/bin:/root/go/bin:${PATH}"
  script:
    - make mpirun
    - >
      until curl --fail http://localhost:10080/kubernetes-ready; do
        sleep 1;
      done
    - make e2e-ci
  after_script:
    - docker stop kind
    - docker rm kind
```

Through the lifecycle of kind container, I see it creates a directory and mount /var/lib/docker.
![image](https://user-images.githubusercontent.com/24671561/63666844-0fae0d00-c804-11e9-8da7-8391847c6b74.png)

But after the container is destroyed, the directory is still there. Therefore, I came up with bug: The node was low on resource: ephemeral-storage.
After cleaning up volumes in docker, it works well again.

# What do I expect
kind can automatically do garbage collection.
looking forward to your reply!
regards

**Comment by nhoughto** [comment]
Interesting, this might explain why others have seen the `ephemeral-storage` problem when not actually out of storage space. We aren't doing anything special with volumes, this is likely a upstream `dind` behaviour, but can look at garbage collection for sure.

**Comment by xial-thu** [comment]
I'm doing gc in my .yaml like
```yaml
after_script:
    - volume_name=$(docker inspect kind -f '{{range .Mounts}}{{.Name}}{{end}}')
    - docker stop kind
    - docker rm kind
    - docker volume rm ${volume_name}
```

Are we able to integration it into kind?

**Comment by nhoughto** [comment]
I can reproduce this if the container is run via:

`docker run -it --privileged bsycorp/kind:latest-1.14`

`docker volume ls` shows a new volume for every run, and `docker ps -a` shows a new exited container too. The problem isn't specifically the volume but the exited container isnt being cleanup. The way you tell docker to cleanup the container (and volumes etc) on exit is via `--rm`, so:

`docker run -it --rm --privileged bsycorp/kind:latest-1.14`

Separately your approach to running it on Gitlab is interesting, is this an on-premise runner? As you should be able to use a Gitlab CI services, rather than start/stop it yourself via:

```
...
build:
  stage: build
  services:
    - bsycorp/kind:latest-1.14
  variables:
    DOCKER_HOST: "tcp://127.0.0.1:2375/"
  script:
...
```
