### ISSUE TITLE
Usage with inherited Dockerfile?

### ISSUE THREAD

**Issue by Ciantic** [bsycorp/kind#26]
This seems like the cleanest way to *learn* and create developer environment for Kubernetes, because docker containers are easy to kill and replicate. You just give the Dockerfile for someone and it's easily reproducible kubernetes environment for learning. 

However I can't figure out how I can call a script in the inherited Dockerfile after the `Kubernetes ready` is printed.

What I need is a way to call a script using ENTRYPOINT or CMD, e.g.

Dockerfile
```
FROM bsycorp/kind:latest-1.15
COPY my.sh /my.sh
CMD [ "/my.sh" ]
```

my.sh
```
#!/bin/bash
/start.sh
# Do my thing here?
# e.g. kubectl apply -f http://example.com ...
```

It fails terribly, for various reasons.

I don't yet quiet understand why this image doesn't have Dockerfile, and seems to be relying on the docker bash scripts.

**Comment by ellieayla** [comment]
ENTRYPOINT and CMD are already defined and do stuff to get supervisord running inside the kind container, which in turn starts other processes like kubelet. Overriding them means taking responsibility for getting supervisord running in your script. But since supervisord doesn't _exit_, you're not going to run anything after it comes up. Don't override ENTRYPOINT+CMD here. 

(You could hack up the supervisord config with additional stuff to start, but that gets more hairy.)

https://github.com/bsycorp/kind/blob/d1441726f6082024a612c654e9f202228ea0219e/build.sh#L56-L57

`kubectl` is normally run on the outside, as part of whatever CI started `kind`

**Comment by Ciantic** [comment]
Hmm, I think the cleanest would be to change the way this `start.sh` ( https://github.com/bsycorp/kind/blob/master/resources/start.sh ) works.

E.g. 

`start.sh`
```
...
echo "Kubernetes ready"
if [ -f "/kubernetes-ready.sh" ]; then
   /bin/bash kubernetes-ready.sh
fi
```

Then I could do simply 

```
FROM bsycorp/kind:latest-1.15
COPY my.sh /kubernetes-ready.sh
```

Or just

```docker run -it --privileged -p 8443:8443 -p 10080:10080 -v $(pwd)/my.sh:/kubernetes-ready.sh bsycorp/kind:latest-1.12```

What do you think?

> kubectl is normally run on the outside, as part of whatever CI started kind

But my use case is different, it's meant for learning and developer environment, where Dockerfile is easisest way to share reproducible environment. This image is so close.

**Comment by nhoughto** [comment]
So there is no Dockerfile because the image needs to be "built" as privileged (because its based on DinD), and there is no option to `docker build ...` with `--privileged` so we need to `docker run..` and then `docker commit` to get the same result, i'll add a kube ready hook script for you to override nps. :+1:

**Comment by nhoughto** [comment]
Done
