### ISSUE TITLE
Why import external RSA pubkey for sgerrand

### ISSUE THREAD

**Issue by WarheadsSE** [bsycorp/kind#4]
In https://github.com/bsycorp/kind/commit/7996bf766268bca61f74b2438317e6987a126049, a change was made from `curl`ing the upstream original to a locally stored and checked in copy of the public signing key for the glibc packages for Alpine by @sgerrand

Why was this done? This will beak any future change to that signing key without a corresponding update to this repository, in a non-sensical method for a user who is not aware of the presence of this file within the repository / project.

**Comment by nhoughto** [comment]
Yeah agree its not great, was originally pulling in the key from remote (which used to be on github), now its hosted elsewhere and that new endpoint appears to be flakey in both local and CI testing, so I moved it into the repo to prevent CI failures for this repo and anyone pulling these scripts in to build their own custom images.

Since we are pinned to a specific version of the glibc package, it shouldn't be _that_ fragile of a setup, if we bump glibc version can update key at the same time. Happy to change back if the URL is more stable :+1:

URL in question is: `https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub`
Failing CI test: https://travis-ci.org/bsycorp/kind/builds/416313339

**Comment by nhoughto** [comment]
Haven't heard anything about stability improvements from upstream, so closing. Pinned version of glibc to pinned version of cert poses no security issues. Happy to change it later if anything changes :+1:
